FROM hub.c.163.com/library/php:7.1-fpm
COPY ./sources.list.jessie /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y \
        libmcrypt-dev \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        && docker-php-ext-install mcrypt \
        && docker-php-ext-install -j$(nproc) iconv mcrypt \
        && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
        && docker-php-ext-install -j$(nproc) gd


## General
RUN docker-php-ext-install pcntl
RUN docker-php-ext-install opcache
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install mbstring

## SOAP Client
RUN apt-get install -y libxml2-dev
RUN docker-php-ext-install soap

## bz2
RUN apt-get install -y libbz2-dev
RUN docker-php-ext-install bz2


#有的系统默认已经安装了curl
#RUN apt-get install -y curl
#RUN apt-get install -y libcurl3
#RUN apt-get install -y libcurl4-openssl-dev
#RUN docker-php-ext-install curl

EXPOSE 9000
